name: Playwright Tests
on:
  workflow_dispatch:

jobs:
  p-test1:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Cache node_modules
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Cache Playwright binaries
      uses: actions/cache@v4
      id: cache-playwright
      with:
        path: |
          C:\Users\runneradmin\AppData\Local\ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}
        enableCrossOsArchive: true
    - name: Install Playwright Browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test tests/example.spec.ts
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: blob-report-1
        path: D:\a\pw-experiment\pw-experiment\all-blob-reports
        retention-days: 2

    - name: Run Playwright tests 2
      run: npx playwright test tests/01test.spec.ts --workers 4
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: blob-report-2
        path: D:\a\pw-experiment\pw-experiment\all-blob-reports
        retention-days: 2
        
    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: blob-report/
        pattern: blob-report-*
        merge-multiple: true

    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html D:\a\pw-experiment\pw-experiment\all-blob-reports
  
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 3
